// src/components/Navbar.tsx
import Link from "next/link";
import { Button } from "~/components/ui/button";

const Navbar = () => {
  return (
    <nav className="bg-background border-b">
      <div className="container mx-auto px-4">
        <div className="flex h-16 items-center justify-between">
          <Link href="/" className="text-xl font-bold">
            flowgress
          </Link>
          <div className="flex space-x-4">
            <Button variant="ghost" asChild>
              <Link href="/">ホーム</Link>
            </Button>
            <Button variant="ghost" asChild>
              <Link href="/about">概要</Link>
            </Button>
            <Button variant="ghost" asChild>
              <Link href="/contact">お問い合わせ</Link>
            </Button>
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// src/lib/components/Navbar.svelte
<script lang="ts">
import { Button } from "$lib/components/ui/button";
</script>

<nav class="bg-primary text-primary-foreground shadow-md">
  <div class="container mx-auto px-4">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <a href="/" class="text-xl font-bold">flowgress</a>
      </div>
      <div class="flex items-center">
        <Button variant="ghost" class="text-primary-foreground">ホーム</Button>
        <Button variant="ghost" class="text-primary-foreground">タスク</Button>
        <Button variant="ghost" class="text-primary-foreground">分析</Button>
        <Button variant="ghost" class="text-primary-foreground">設定</Button>
      </div>
    </div>
  </div>
</nav>
